### ISSUE TITLE
[Bug]: The same _file_offset in the Change Store causes data duplication even if there is a primary key table with upsert enabled

### ISSUE THREAD

**Issue by shendanfengg** [NetEase/arctic#1025]
### What happened?

For tables with a primary key and the property 'write.upsert.enabled' set, when the same transaction id commits multiple changes to a primary key data, it can lead to data duplication. And the '_file_offset' of these duplicate data must be duplicated.
![image](https://user-images.githubusercontent.com/109209550/215317243-20b62ecb-b7cc-42cb-978f-57c76e9aa223.png)

### Affects Versions

0.3.x

### What engines are you seeing the problem on?

Flink

### How to reproduce

1.Create an Arctic table with a primary key and start a Flink ingestion job
2.The same primary key is used for Insert and Update operations during a single transaction commit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by zhoujinsong** [comment]
@zstraw @shendanfengg  any progress on this issue?

**Comment by zstraw** [comment]
> @zstraw @shendanfengg any progress on this issue?

I reproduce this problem locally. It's caused by the nonstandard data stream with multi update_after data but without update_before.

https://github.com/NetEase/arctic/blob/master/core/src/main/java/com/netease/arctic/io/writer/ChangeTaskWriter.java#L86
The fileOffset won't increment if the rowkind is UA.

**Comment by zstraw** [comment]
> @zstraw @shendanfengg any progress on this issue?

I reproduce this problem locally. It's caused by the nonstandard data stream with multi update_after data but without update_before or the disorder of data stream.

https://github.com/NetEase/arctic/blob/master/core/src/main/java/com/netease/arctic/io/writer/ChangeTaskWriter.java#L86
The fileOffset won't increment if the rowkind is UA.  So if the data stream incoming is like UB, UB, I, UA, UA, the fileOffsets would be wrong.
