### ISSUE TITLE
[Bug]: High CPU occupancy of AMS

### ISSUE THREAD

**Issue by wangtaohz** [NetEase/arctic#1332]
### What happened?

After start AMS, Trash worker thread occupies 100% CPU.

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/103108928/231364025-0ecd4e2b-eda9-40a7-88fc-4fa12182f0ae.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/103108928/231363903-daaaedbb-75a5-4e08-b125-540abd4f6edb.png">

### Affects Versions

master/0.4.1

### What engines are you seeing the problem on?

AMS

### How to reproduce

1. Set `conf/config.yaml`, remove `arctic.ams.trash.clean.thread.pool-size`, or set it to `0`
2. restart AMS

### Anything else

It happens every time.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangtaohz** [comment]
It is a bug of jdk 8, we can get more details [here](https://josephmate.github.io/2021-10-03-my-bug-used-up-100cpu-or-did-it/) .

I believe the simplest solution is to avoid setting corePoolSize to 0 when using `ScheduledThreadPoolExecutor`.

That means if we set thread pool size to 0 in the AMS config file, we should not create a `ScheduledThreadPoolExecutor`.

**Comment by wangtaohz** [comment]
The same problem can be reproduced in version 0.5.0.
<img width="901" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/51a5a63c-7c72-4f25-891c-56dffe0b5437">
<img width="1913" alt="image" src="https://github.com/NetEase/arctic/assets/103108928/5c1cee24-aeaa-467c-8b72-4854a86c02a9">

**Comment by zhoujinsong** [comment]
@wangtaohz Thanks a lot for reporting this issue.

AFAIK, there is no longer a trash cleaning function and related parameter "trash.clean.thread.pool-size" since version 0.5.0. The default concurrency of other executor-related functions is greater than 0.

But we still need to discuss how to handle the situation when the concurrency of other executors is set to 0 or a smaller value, for example: 

1. Setting it to a negative number is obviously an incorrect configuration, so we should throw an error during parameter checking, prompting the user to modify the parameter and restart.
2. If it is set to 0, does it mean that the user does not need this background thread to perform the corresponding work? Is this allowed by our system, such as closing the commit executor will cause the core function of AMS self-optimization to not work properly? Should we require that the concurrency configuration of all executors be greater than 0 to avoid this problem?
3. If we allow some functions to not initialize these background threads, should we open a separate configuration for declaration instead of directly setting the concurrency to 0?

**Comment by wangtaohz** [comment]
> 1.Setting it to a negative number is obviously an incorrect configuration, so we should throw an error during parameter checking, prompting the user to modify the parameter and restart.

I agree with this, do you think I should add a configuration check mechanism for fixing this issue?

For 2, I think a mechanism should be provided to avoid starting the background thread pool because some features may be irrelevant to the user, such as Hive sync. The risk of disabling a useful thread pool (such as commit thread pool) would be worth it, because users should be aware of the purpose of thread pools when they disable them.

> 3.If we allow some functions to not initialize these background threads, should we open a separate configuration for declaration instead of directly setting the concurrency to 0?

For 3, I prefer to `directly setting the concurrency to 0`, because this is clear and intuitive. On the contrary, if there are two configurations, xxx.enabled and xxx.thread-pool.size, and the user sets xxx.enable=false and xxx.thread-pool.size=10, it is ambiguous whether thread resources are closed or not.
