### ISSUE TITLE
[Bug][Spark]: The data are written repeatedly after the Spark Executor failover

### ISSUE THREAD

**Issue by hellojinsilei** [NetEase/arctic#917]
### What happened?

When after running the Spark insert command, more data is written. And on Spark UI, there are many Executors that have failover. 
If Executor does not failover, the amount of data observed is correct

### Affects Versions

0.3.2

### What engines are you seeing the problem on?

Spark

### How to reproduce

Running the Spark insert command, if the executor has failover, the problem will be reproduced

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baiyangtx** [comment]
The reason may be caused by the executor's attempts, if some executor failed and re-run by spark context, the failed executor has already written some data files and those files will not be deleted.

To solve this,  the spark writer should write files starting with a `.`  as hidden files, and rename files to non-hidden files when the task commits for the arctic hive table.

**Comment by baiyangtx** [comment]
The final solution:  handle orphan files when overwrite commit. 

During spark overwrite is committing,  the spark driver will list partition files for new creation partitions or partitions that have a new location,  the spark driver needs to delete files which not exist in the overwrite operation added files set.  This action will happen before the iceberg table commit.
